### ISSUE TITLE
Linux compile error

### ISSUE THREAD

**Issue by seriousuncle** [Lecrapouille/TimedPetriNetEditor#10]
i finished compile in linux :
```
cd TimedPetriNetEditor/
make download-external-libs
make -j8"
```

but when i run:
```
./build/TimedPetriNetEditor
```
encounter an error:
```
root@www:/home/vboxuser/Petri/TimedPetriNetEditor# ld/TimedPetriNetEditor
Setting vertical sync not supported
X Error of failed request: BadshmSeg (invalid shared segment parameter)
Major opcode of failed request:130 (MIT-SHM)
Minor opcode of failed request: 3  (X_ShmPutImage)
Segment id in failed request:0xa00026
Serial number of failed request:176
Current serial number in output stream:177
```

**Comment by Lecrapouille** [comment]
@seriousuncle hi ! Thanks you for your concern about this project. Your issue is more related to a driver issue on your Linux. I'm using the lib [SFML ](https://github.com/SFML/SFML) and [DearImGui](https://github.com/ocornut/imgui). This maybe related to your issue: https://github.com/termux/termux-x11/issues/234 If you have a second computer you can compile to check if this issue is still present.

**Comment by Lecrapouille** [comment]
@seriousuncle I close since missing feedback from you. Feel reopen it if needed
